/-
Copyright (c) 2026 OpenAI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI
-/
module

public import SeriesParallel.MainText.LogGates
public import SeriesParallel.MainText.Networks
public import SeriesParallel.MainText.TreeEnvironment

/-!
# The random series--parallel network on the common tree environment

The network at every depth is a deterministic function of one infinite Bernoulli environment.
This is the common coupling needed for almost-sure statements and adjacent-generation estimates.

## Main results

- `randomNetwork_refinement`: the exact samplewise conditional-refinement decomposition.
- `Z_succ`: the unified series/parallel recursion before passing to laws.
- `randomNetwork_complement`: complementation exchanges every series and parallel gate.
- `resistanceValue_complement`: the strong samplewise resistance duality.
-/

@[expose] public section

namespace SeriesParallel.MainText

/-- The depth-`n` two-terminal network generated by one common environment. -/
def randomNetwork : ℕ → Environment → SPNetwork
  | 0, _ => .edge
  | n + 1, environment =>
      let left := randomNetwork n (Environment.subtree [false] environment)
      let right := randomNetwork n (Environment.subtree [true] environment)
      if environment root then .series left right else .parallel left right

@[simp]
theorem randomNetwork_zero (environment : Environment) :
    randomNetwork 0 environment = .edge := rfl

theorem randomNetwork_succ_series {n : ℕ} {environment : Environment}
    (hroot : environment root = true) :
    randomNetwork (n + 1) environment =
      .series (randomNetwork n (Environment.subtree [false] environment))
        (randomNetwork n (Environment.subtree [true] environment)) := by
  simp [randomNetwork, hroot]

theorem randomNetwork_succ_parallel {n : ℕ} {environment : Environment}
    (hroot : environment root = false) :
    randomNetwork (n + 1) environment =
      .parallel (randomNetwork n (Environment.subtree [false] environment))
        (randomNetwork n (Environment.subtree [true] environment)) := by
  simp [randomNetwork, hroot]

/-- Every depth-`n` realization has exactly `2^n` unit edges. -/
@[simp]
theorem randomNetwork_edgeCount (n : ℕ) (environment : Environment) :
    (randomNetwork n environment).edgeCount = 2 ^ n := by
  induction n generalizing environment with
  | zero => simp
  | succ n ih =>
      by_cases hroot : environment root
      · simp [randomNetwork, hroot, ih, pow_succ]
        omega
      · simp [randomNetwork, hroot, ih, pow_succ]
        omega

/-- Graph distance in the canonical depth-`n` realization. -/
def distanceValue (n : ℕ) (environment : Environment) : ℕ :=
  (randomNetwork n environment).distance

/-- Effective resistance in the canonical depth-`n` realization. -/
noncomputable def resistanceValue (n : ℕ) (environment : Environment) : ℝ :=
  (randomNetwork n environment).resistance

/-- The unified positive quantity `Z_n^(η)`, represented as a real number in both modes. -/
noncomputable def Z (mode : Mode) (n : ℕ) (environment : Environment) : ℝ :=
  match mode with
  | .distance => distanceValue n environment
  | .resistance => resistanceValue n environment

/-- The logarithmic quantity `X_n^(η) = log Z_n^(η)`. -/
noncomputable def X (mode : Mode) (n : ℕ) (environment : Environment) : ℝ :=
  Real.log (Z mode n environment)

@[simp]
theorem distanceValue_zero (environment : Environment) : distanceValue 0 environment = 1 := rfl

@[simp]
theorem resistanceValue_zero (environment : Environment) :
    resistanceValue 0 environment = 1 := rfl

@[simp]
theorem Z_zero (mode : Mode) (environment : Environment) : Z mode 0 environment = 1 := by
  cases mode <;> simp [Z, distanceValue, resistanceValue]

theorem distanceValue_pos (n : ℕ) (environment : Environment) :
    0 < distanceValue n environment :=
  (randomNetwork n environment).distance_pos

theorem resistanceValue_pos (n : ℕ) (environment : Environment) :
    0 < resistanceValue n environment :=
  (randomNetwork n environment).resistance_pos

@[simp]
theorem distanceValue_succ (n : ℕ) (environment : Environment) :
    distanceValue (n + 1) environment =
      if environment root then
        distanceValue n (Environment.subtree [false] environment) +
          distanceValue n (Environment.subtree [true] environment)
      else
        min (distanceValue n (Environment.subtree [false] environment))
          (distanceValue n (Environment.subtree [true] environment)) := by
  by_cases hroot : environment root <;> simp [distanceValue, randomNetwork, hroot]

@[simp]
theorem resistanceValue_succ (n : ℕ) (environment : Environment) :
    resistanceValue (n + 1) environment =
      if environment root then
        resistanceValue n (Environment.subtree [false] environment) +
          resistanceValue n (Environment.subtree [true] environment)
      else
        resistanceValue n (Environment.subtree [false] environment) *
            resistanceValue n (Environment.subtree [true] environment) /
          (resistanceValue n (Environment.subtree [false] environment) +
            resistanceValue n (Environment.subtree [true] environment)) := by
  by_cases hroot : environment root <;> simp [resistanceValue, randomNetwork, hroot]

theorem Z_pos (mode : Mode) (n : ℕ) (environment : Environment) :
    0 < Z mode n environment := by
  cases mode with
  | distance =>
      change 0 < (distanceValue n environment : ℝ)
      exact_mod_cast distanceValue_pos n environment
  | resistance => exact resistanceValue_pos n environment

theorem Z_ne_zero (mode : Mode) (n : ℕ) (environment : Environment) :
    Z mode n environment ≠ 0 :=
  (Z_pos mode n environment).ne'

/-- The exact samplewise unified recursion (`eq:unified-rde` before taking laws). -/
theorem Z_succ (mode : Mode) (n : ℕ) (environment : Environment) :
    Z mode (n + 1) environment =
      if environment root then
        seriesGate (Z mode n (Environment.subtree [false] environment))
          (Z mode n (Environment.subtree [true] environment))
      else
        parallelGate mode (Z mode n (Environment.subtree [false] environment))
          (Z mode n (Environment.subtree [true] environment)) := by
  cases mode with
  | distance =>
      by_cases hroot : environment root
      · simp [Z, distanceValue, randomNetwork, hroot, seriesGate]
      · simp [Z, distanceValue, randomNetwork, hroot]
  | resistance =>
      by_cases hroot : environment root
      · simp [Z, resistanceValue, randomNetwork, hroot, seriesGate]
      · simp only [Z, resistanceValue, randomNetwork, hroot]
        rw [parallelGate_resistance_eq_harmonic]
        · rfl
        · exact (randomNetwork n (Environment.subtree [false] environment)).resistance_pos
        · exact (randomNetwork n (Environment.subtree [true] environment)).resistance_pos

/-- The exact logarithmic recursion (`eq:log-rde` before taking laws). -/
theorem X_succ (mode : Mode) (n : ℕ) (environment : Environment) :
    X mode (n + 1) environment =
      if environment root then
        logSeriesGate (X mode n (Environment.subtree [false] environment))
          (X mode n (Environment.subtree [true] environment))
      else
        logParallelGate mode (X mode n (Environment.subtree [false] environment))
          (X mode n (Environment.subtree [true] environment)) := by
  rw [X, Z_succ]
  by_cases hroot : environment root
  · simp [hroot]
    rw [log_seriesGate]
    · rfl
    · exact Z_pos mode n (Environment.subtree [false] environment)
    · exact Z_pos mode n (Environment.subtree [true] environment)
  · simp [hroot]
    rw [log_parallelGate]
    · rfl
    · exact Z_pos mode n (Environment.subtree [false] environment)
    · exact Z_pos mode n (Environment.subtree [true] environment)

/-- Refining by `r` generations is exactly leaf substitution by the descendant networks. -/
theorem randomNetwork_refinement (n r : ℕ) (environment : Environment) :
    randomNetwork (n + r) environment =
      (randomNetwork n environment).substitute
        (fun word ↦ randomNetwork r (Environment.subtree word environment)) := by
  induction n generalizing environment with
  | zero =>
      have hsubtree : Environment.subtree ([] : Word) environment = environment := by
        rfl
      simp [hsubtree]
  | succ n ih =>
      rw [Nat.succ_add]
      cases hroot : environment root with
      | false =>
        rw [randomNetwork_succ_parallel hroot, randomNetwork_succ_parallel hroot,
          SPNetwork.substitute_parallel]
        apply congrArg₂ SPNetwork.parallel
        · rw [ih]
          congr 1
        · rw [ih]
          congr 1
      | true =>
        rw [randomNetwork_succ_series hroot, randomNetwork_succ_series hroot,
          SPNetwork.substitute_series]
        apply congrArg₂ SPNetwork.series
        · rw [ih]
          congr 1
        · rw [ih]
          congr 1

/-- Complementing the environment exchanges series and parallel at every gate. -/
theorem randomNetwork_complement (n : ℕ) (environment : Environment) :
    randomNetwork n (complementEnvironment environment) =
      (randomNetwork n environment).dual := by
  induction n generalizing environment with
  | zero => rfl
  | succ n ih =>
      by_cases hroot : environment root
      · simp [randomNetwork, hroot]
        constructor
        · change randomNetwork n
            (complementEnvironment (Environment.subtree [false] environment)) = _
          exact ih _
        · change randomNetwork n
            (complementEnvironment (Environment.subtree [true] environment)) = _
          exact ih _
      · simp [randomNetwork, hroot]
        constructor
        · change randomNetwork n
            (complementEnvironment (Environment.subtree [false] environment)) = _
          exact ih _
        · change randomNetwork n
            (complementEnvironment (Environment.subtree [true] environment)) = _
          exact ih _

/-- The strong samplewise form of resistance duality. -/
theorem resistanceValue_complement (n : ℕ) (environment : Environment) :
    resistanceValue n (complementEnvironment environment) =
      (resistanceValue n environment)⁻¹ := by
  rw [resistanceValue, randomNetwork_complement, resistanceValue,
    SPNetwork.resistance_dual]

/-- The source logarithmic duality, still as a samplewise identity. -/
theorem log_resistanceValue_complement (n : ℕ) (environment : Environment) :
    Real.log (resistanceValue n (complementEnvironment environment)) =
      -Real.log (resistanceValue n environment) := by
  rw [resistanceValue_complement, Real.log_inv]

/-- Both unified quantities are bounded above by the number of leaves. -/
theorem Z_le_two_pow (mode : Mode) (n : ℕ) (environment : Environment) :
    Z mode n environment ≤ (2 : ℝ) ^ n := by
  cases mode with
  | distance =>
      change (distanceValue n environment : ℝ) ≤ (2 : ℝ) ^ n
      have hbound : distanceValue n environment ≤ 2 ^ n :=
        (randomNetwork n environment).distance_bounds.2.trans_eq
          (randomNetwork_edgeCount n environment)
      exact_mod_cast hbound
  | resistance =>
      calc
        resistanceValue n environment
            ≤ (randomNetwork n environment).edgeCount :=
              (randomNetwork n environment).resistance_le_edgeCount
        _ = ((2 : ℕ) ^ n : ℝ) := by exact_mod_cast randomNetwork_edgeCount n environment
        _ = (2 : ℝ) ^ n := by norm_num

end SeriesParallel.MainText
